name: Quest Ticket
description: Add or modify a quest
body:
  - type: input
    attributes: { label: City, placeholder: emotion|passion|intellect|willpower|memory|imagination|silence }
    validations: { required: true }
  - type: textarea
    attributes: { label: Prompt, description: User-facing text }
    validations: { required: true }
  - type: checkboxes
    attributes:
      label: Requires
      options:
        - label: text
        - label: steps
        - label: location
        - label: stillness
        - label: weather
  - type: textarea
    attributes: { label: Completion rule, description: e.g. steps>=2000 or text length>=3 }
