openapi: 3.0.3
info: { title: Atlas API, version: "1.0.0" }
paths:
  /v1/quests/today:
    get: { responses: { "200": { description: OK } } }
  /v1/quests/{id}/submit:
    post: { parameters: [{in: path, name: id, required: true}], responses: {"200": {description: OK}} }
  /v1/atlas:
    get: { responses: { "200": { description: OK } } }
