name: Quest Ticket
description: Add or modify a quest (reflection/action/release/sensor)
title: "[Quest] "
labels: ["quest"]
body:
  - type: input
    id: city
    attributes:
      label: City
      placeholder: emotion | passion | intellect | willpower | memory | imagination | silence
    validations: { required: true }

  - type: dropdown
    id: kind
    attributes:
      label: Quest kind
      options: [reflection, action, release, sensor]
    validations: { required: true }

  - type: textarea
    id: prompt
    attributes:
      label: Prompt (user-facing)
      placeholder: "If it’s raining, step outside for 2 minutes and name the feeling that rises."
    validations: { required: true }

  - type: checkboxes
    id: requires
    attributes:
      label: Requires
      options:
        - label: text
        - label: steps
        - label: location
        - label: stillness
        - label: weather

  - type: textarea
    id: rule
    attributes:
      label: Completion rule
      placeholder: "steps>=2000"

  - type: textarea
    id: artifacts
    attributes:
      label: Artifacts / effects
      placeholder: ripple | torch | stone | lantern | tree | shard

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      placeholder: "Submitting the quest adds a ripple to Emotion and updates atlas state."

  - type: textarea
    id: notes
    attributes:
      label: Notes / safety
